# Generated by Django 5.0.1 on 2024-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaEstadoSolicitudes',
            fields=[
                ('mes', models.IntegerField(primary_key=True, serialize=False)),
                ('num_aprobadas', models.IntegerField()),
                ('num_en_proceso', models.IntegerField()),
                ('num_no_aprobadas', models.IntegerField()),
                ('num_canceladas', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_estado_solicitudes',
                'managed': False,
            },
        ),
    ]
