# Generated by Django 4.1.13 on 2024-04-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aprobacionesservicios_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMedica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estatus', models.IntegerField(blank=True, db_column='Estatus', null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'areas_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('responsable_id', models.PositiveIntegerField(blank=True, db_column='Responsable_id', null=True)),
                ('estatus', models.IntegerField(db_column='Estatus')),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=45, null=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=80)),
                ('primer_apellido', models.CharField(db_column='Primer_Apellido', max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, db_column='Segundo_Apellido', max_length=80, null=True)),
                ('curp', models.CharField(blank=True, db_column='CURP', max_length=20, null=True)),
                ('genero', models.CharField(db_column='Genero', max_length=3)),
                ('grupo_sanguineo', models.CharField(db_column='Grupo_Sanguineo', max_length=2)),
                ('tipo_sanguineo', models.CharField(db_column='Tipo_Sanguineo', max_length=1)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('estatus', models.TextField(db_column='Estatus')),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaCantidadPacientes',
            fields=[
                ('cantidad_total_personas', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_femeninos', models.IntegerField()),
                ('cantidad_masculinos', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaCantidadPersonalMedico',
            fields=[
                ('medicos', models.IntegerField(primary_key=True, serialize=False)),
                ('enfermeros', models.IntegerField()),
                ('administrativos', models.IntegerField()),
                ('directivos', models.IntegerField()),
                ('apoyo', models.IntegerField()),
                ('residentes', models.IntegerField()),
                ('internos', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_cantidad_personal_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaOperacionesBitacora',
            fields=[
                ('inserciones', models.IntegerField(primary_key=True, serialize=False)),
                ('actualizaciones', models.IntegerField()),
                ('eliminaciones', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_operaciones_bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='c_detalle_lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_Lotes_ID', models.CharField(max_length=15)),
                ('di_Codigo', models.CharField(max_length=15)),
                ('di_Marca', models.CharField(max_length=50)),
                ('di_Precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('di_Estatus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='c_detalles_dispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_Dispensacion_ID', models.CharField(max_length=15)),
                ('di_Detalle_Receta_ID', models.CharField(max_length=15)),
                ('di_Fecha_Entrega', models.DateTimeField(auto_now_add=True)),
                ('di_Cantidad_Entregada', models.IntegerField()),
                ('di_Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('di_Precio_Total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='c_dispensacion_medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_Receta_ID', models.CharField(max_length=15)),
                ('di_Personal_Medico_ID', models.CharField(max_length=15)),
                ('di_Fecha_Registro', models.DateTimeField(auto_now_add=True)),
                ('di_Total_Medicamentos_Solicitados', models.IntegerField()),
                ('di_Total_Medicamentos_Entregados', models.IntegerField()),
                ('di_estatus', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='c_lotes_medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_Medicamento_ID', models.CharField(max_length=15)),
                ('di_Descripcion', models.CharField(max_length=15)),
                ('di_Cantidad', models.IntegerField()),
                ('di_fecha_vencimiento', models.DateField()),
                ('di_fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='organos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('aparato_sistema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('especificaciones', models.TextField()),
                ('restricciones', models.TextField()),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_transplantes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('paciente_ID', models.IntegerField()),
                ('medico_ID', models.IntegerField()),
                ('organo_ID', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Moderada', 'Moderada')], max_length=255)),
                ('fecha_solicitud', models.DateTimeField()),
                ('dias_espera', models.IntegerField()),
                ('estatus', models.CharField(choices=[('Transplante exitoso', 'Transplante Exitoso'), ('Recuperacion', 'Recuperacion'), ('Pendiente', 'Pendiente')], max_length=255)),
                ('estatus_aprobacion', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='c_dispensacion',
        ),
        migrations.DeleteModel(
            name='c_inventario',
        ),
        migrations.DeleteModel(
            name='solicitud_organos_1',
        ),
        migrations.AlterModelOptions(
            name='aprobacionesservicios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bitacoradg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicioshospitalarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='serviciosmedicos',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('persona', models.OneToOneField(db_column='Persona_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.personas')),
                ('nss', models.CharField(blank=True, db_column='NSS', max_length=15, null=True, unique=True)),
                ('tipo_seguro', models.CharField(db_column='Tipo_Seguro', max_length=50)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_ultimacita', models.DateTimeField(db_column='Fecha_UltimaCita')),
                ('estatus_medico', models.CharField(blank=True, db_column='Estatus_Medico', max_length=100, null=True)),
                ('estatus_vida', models.CharField(db_column='Estatus_Vida', max_length=10)),
                ('estatus', models.TextField(blank=True, db_column='Estatus', null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('persona', models.OneToOneField(db_column='Persona_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.personas')),
                ('especialidad', models.CharField(blank=True, db_column='Especialidad', max_length=50, null=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=14)),
                ('cedula_profesional', models.IntegerField(blank=True, db_column='Cedula_Profesional', null=True, unique=True)),
                ('estatus', models.TextField(db_column='Estatus')),
                ('fecha_contratacion', models.DateTimeField(db_column='Fecha_Contratacion')),
                ('fecha_terminacion_contrato', models.DateTimeField(blank=True, db_column='Fecha_Terminacion_Contrato', null=True)),
            ],
            options={
                'db_table': 'personal_medico',
                'managed': False,
            },
        ),
    ]
