# Generated by Django 5.0.1 on 2024-04-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aprobacionesservicios_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas_medicas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, choices=[('Sr.', 'Sr.'), ('Sra.', 'Sra.'), ('Srta.', 'Srta.'), ('Dr.', 'Dr.'), ('Dra.', 'Dra.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Prof.', 'Prof.'), ('Otro', 'Otro')], max_length=45, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('curp', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/B', 'No binario')], max_length=3)),
                ('grupo_sanguineo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('tipo_sanguineo', models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('area_medica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.areamedica')),
                ('departamento_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Médico', 'Médico'), ('Enfermero', 'Enfermero'), ('Administrativo', 'Administrativo'), ('Directivo', 'Directivo'), ('Apoyo', 'Apoyo'), ('Residente', 'Residente'), ('Interno', 'Interno')], max_length=20)),
                ('cedula_profesional', models.PositiveIntegerField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Jubilado', 'Jubilado'), ('Permiso', 'Permiso')], default='Activo', max_length=20)),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_terminacion_contrato', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_medico', to='api.departamento')),
            ],
            options={
                'db_table': 'personal_medico',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsable', to='api.personalmedico'),
        ),
    ]
