# Generated by Django 5.0.1 on 2024-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_areamedica_persona_departamento_personalmedico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estatus',
            field=models.IntegerField(default=1),
        ),
    ]
