# Generated by Django 5.0.1 on 2024-04-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_departamento_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaCantidadPersonalMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicos', models.IntegerField()),
                ('enfermeros', models.IntegerField()),
                ('administrativos', models.IntegerField()),
                ('directivos', models.IntegerField()),
                ('apoyo', models.IntegerField()),
                ('residentes', models.IntegerField()),
                ('internos', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_cantidad_personal_medico',
                'managed': False,
            },
        ),
    ]
