# Generated by Django 5.0.1 on 2024-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vistacantidadpersonalmedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaCantidadPacientes',
            fields=[
                ('cantidad_total_personas', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_femeninos', models.IntegerField()),
                ('cantidad_masculinos', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaOperacionesBitacora',
            fields=[
                ('inserciones', models.IntegerField(primary_key=True, serialize=False)),
                ('actualizaciones', models.IntegerField()),
                ('eliminaciones', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_bitacora',
                'managed': False,
            },
        ),
    ]
