# Generated by Django 4.1.13 on 2024-04-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pacientes_alter_aprobacionesservicios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aprobacionesservicios',
            table='api_aprobacionesservicios',
        ),
        migrations.AlterModelTable(
            name='bitacoradg',
            table='api_bitacoradg',
        ),
        migrations.AlterModelTable(
            name='servicioshospitalarios',
            table='api_servicioshospitalarios',
        ),
        migrations.AlterModelTable(
            name='serviciosmedicos',
            table='api_serviciosmedicos',
        ),
    ]
