# Generated by Django 4.1.13 on 2024-04-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aprobacionesservicios_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pacientes',
            table='api_pacientes',
        ),
    ]
