# Generated by Django 4.1.13 on 2024-04-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pacienteshg_delete_pacientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteshg',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
