# Generated by Django 4.1.13 on 2024-04-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pacienteshg_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasMedicas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estatus', models.IntegerField(blank=True, db_column='Estatus', null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'areas_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('responsable_id', models.PositiveIntegerField(blank=True, db_column='Responsable_id', null=True)),
                ('estatus', models.IntegerField(db_column='Estatus')),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=45, null=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=80)),
                ('primer_apellido', models.CharField(db_column='Primer_Apellido', max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, db_column='Segundo_Apellido', max_length=80, null=True)),
                ('curp', models.CharField(blank=True, db_column='CURP', max_length=20, null=True)),
                ('genero', models.CharField(db_column='Genero', max_length=3)),
                ('grupo_sanguineo', models.CharField(db_column='Grupo_Sanguineo', max_length=2)),
                ('tipo_sanguineo', models.CharField(db_column='Tipo_Sanguineo', max_length=1)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('estatus', models.TextField(db_column='Estatus')),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='area_medica',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='departamento_superior',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='responsable',
        ),
        migrations.AlterModelTable(
            name='aprobacionesservicios',
            table='aprobaciones_servicios',
        ),
        migrations.AlterModelTable(
            name='bitacoradg',
            table='bitacora_dg',
        ),
        migrations.AlterModelTable(
            name='servicioshospitalarios',
            table='servicios_hospitalarios',
        ),
        migrations.AlterModelTable(
            name='serviciosmedicos',
            table='instalaciones',
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('persona', models.OneToOneField(db_column='Persona_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.personas')),
                ('nss', models.CharField(blank=True, db_column='NSS', max_length=15, null=True, unique=True)),
                ('tipo_seguro', models.CharField(db_column='Tipo_Seguro', max_length=50)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_ultimacita', models.DateTimeField(db_column='Fecha_UltimaCita')),
                ('estatus_medico', models.CharField(blank=True, db_column='Estatus_Medico', max_length=100, null=True)),
                ('estatus_vida', models.CharField(db_column='Estatus_Vida', max_length=10)),
                ('estatus', models.TextField(blank=True, db_column='Estatus', null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PacientesHG',
        ),
        migrations.DeleteModel(
            name='AreaMedica',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
