# Generated by Django 4.1.13 on 2024-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_areasmedicas_departamentos_personas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMedica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estatus', models.IntegerField(blank=True, db_column='Estatus', null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', null=True)),
            ],
            options={
                'db_table': 'areasmedicas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AreasMedicas',
        ),
    ]
