# Generated by Django 4.1.13 on 2024-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteArea',
            fields=[
                ('area_medica', models.AutoField(primary_key=True, serialize=False)),
                ('pacientes_en_atencion', models.CharField(max_length=50)),
                ('medicos_disponibles', models.CharField(max_length=50)),
                ('enfermeras_disponibles', models.CharField(max_length=50)),
                ('pasantes_asignados', models.CharField(max_length=50)),
                ('residentes_asignados', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PacientesConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('numero_recetas', models.CharField(max_length=50)),
                ('numero_estudios_clinicos', models.CharField(max_length=50)),
                ('numero_ingresos', models.CharField(max_length=50)),
            ],
        ),
    ]
