from django.contrib import admin
from .models import c_cliente,c_rol,c_registrosM, c_cirugia,c_Solicitud_Cirugias, nacimientos_bebes,seguimiento_pediatria,c_receta_medica,c_receta_medica_detalles,ServiciosMedicos, ServiciosHospitalarios, AprobacionesServicios,BitacoraDG,Departamentos,AreaMedica,Personas,Pacientes, PersonalMedico, Puesto, Horario, Personal

# Register your models here.
admin.site.register(nacimientos_bebes)
admin.site.register(seguimiento_pediatria)
admin.site.register(c_cliente)
admin.site.register(c_rol)
admin.site.register(c_registrosM)
admin.site.register(c_cirugia)
admin.site.register(c_Solicitud_Cirugias)
# admin.site.register(c_dispensacion_medicamentos)
admin.site.register(c_receta_medica)
admin.site.register(c_receta_medica_detalles)
# admin.site.register(c_detalles_dispensacion)
# admin.site.register(c_lotes_medicamentos)
# admin.site.register(c_detalle_lotes)
admin.site.register(ServiciosMedicos)
admin.site.register(ServiciosHospitalarios)
admin.site.register(AprobacionesServicios)
admin.site.register(BitacoraDG)
admin.site.register(Departamentos)
admin.site.register(AreaMedica)
admin.site.register(Personas)
admin.site.register(PersonalMedico)
admin.site.register(Pacientes)
admin.site.register(Puesto)
admin.site.register(Horario)
admin.site.register(Personal)
